"""Carve the N1510 validation cohort (323 subjects) into 80% validation +
20% held-out test, patient-level random split with fixed seed.

Writes a new datalist file; leaves the original untouched. The training
partition is copied verbatim.

Output: datalist_N1510_split.json with keys
  training   (1187, unchanged)
  validation (~258, 80% of original validation)
  testing    (~65, held-out)

Both Paper A (TSTR-seg) and Paper B (inpainting) use this split.
"""
import json
import random
from pathlib import Path

SEED = 42
SRC = Path(__file__).resolve().parent.parent / "datalist_N1510.json"
DST = SRC.with_name("datalist_N1510_split.json")
TEST_FRAC = 0.20


def main() -> None:
    d = json.loads(SRC.read_text())

    val = list(d["validation"])
    rng = random.Random(SEED)
    rng.shuffle(val)

    n_test = round(len(val) * TEST_FRAC)
    testing = val[:n_test]
    validation = val[n_test:]

    out = {
        "training":   d["training"],
        "validation": validation,
        "testing":    testing,
        "n_training":   len(d["training"]),
        "n_validation": len(validation),
        "n_testing":    len(testing),
        "n_subjs":      len(d["training"]) + len(validation) + len(testing),
        "_provenance":  f"Generated by split_validation_80_20.py from {SRC.name} (seed={SEED})",
    }
    DST.write_text(json.dumps(out, indent=2))
    print(f"Wrote {DST}")
    print(f"  training   {out['n_training']}")
    print(f"  validation {out['n_validation']}")
    print(f"  testing    {out['n_testing']}")


if __name__ == "__main__":
    main()
